name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:https://github.com/MKYGRAPHICS7/Poco-M6-Plus-Breeze-Device-Tree:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
